baseURL = 'https://blanksy.org'
languageCode = 'en-us'
title = 'blanksy .org'

theme = "paper"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
